# Generated by Django 5.1.2 on 2024-10-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(auto_created=True, verbose_name='Вотстольколетназадслучилсяапокалипсисаименнотвоёрождение')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('age', models.IntegerField(verbose_name='хыхыдед')),
                ('IsFemboy', models.BooleanField(default=True, verbose_name='увыиах')),
            ],
        ),
    ]
