# Generated by Django 5.1.2 on 2024-11-06 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkusna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='IsFemboy',
            field=models.BooleanField(default=True, verbose_name='наличие пениса'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(auto_created=True, verbose_name='Дата Рождения'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название пикчи')),
                ('path', models.FileField(upload_to='', verbose_name='Путь пикчи')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='vkusna.user', verbose_name='Пользователь')),
            ],
        ),
    ]
