# Generated by Django 5.1.2 on 2024-11-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkusna', '0002_alter_user_isfemboy_alter_user_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ФавФетиш')),
                ('Number_of_views', models.IntegerField(verbose_name='Просмотры')),
                ('Dumbness', models.BooleanField(default=False, verbose_name='Тупость')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(verbose_name='Длина')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('Number_of_views', models.IntegerField(verbose_name='Просмотры')),
            ],
        ),
    ]
