# Generated by Django 5.1.2 on 2024-11-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkusna', '0005_user_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='path',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Путь видео'),
        ),
    ]
